# Source: https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html#example-1

name: Continuous Integration
permissions: read-all|write-all
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'lib/**'
      - 'coverage/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v2

    # Build steps
    - uses: actions/setup-node@v3
      with:
        node-version: '14' 
    - name: Node Install
      run: npm install
    - name: Node Build (lint, test, coverage, doc, build, package)
      run: npm run build

    # Commit and push all changed files.
    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push